### ISSUE TITLE
这行代码报空？

### ISSUE THREAD

**Issue by MarkCHYL** [bambootang/ViewPager3D#1]
reflectView.updateReflect();

**Comment by bambootang** [comment]
直接跑的demo吗？
可以把报错日志的堆栈信息提供一下吗？

**Comment by bambootang** [comment]
demo 没有出现这个问题，是不是你传了个空view过去？ 
麻烦提供一下错误日志重新提1下issue。非常感谢～🙏。

**Comment by MarkCHYL** [comment]
我用的是就是demo中的那个类啊

**Comment by MarkCHYL** [comment]
java.lang.NullPointerException: Attempt to invoke virtual method 'int android.graphics.Bitmap.getWidth()' on a null object reference
                                                                             at com.bambootang.viewpager3d.ImageReflect.convertViewToBitmap(ImageReflect.java:30)
                                                                             at com.bambootang.viewpager3d.ReflectView.updateReflect(ReflectView.java:59)
                                                                             at com.viewpager3d_demo.mark.Simple03Activity$1.instantiateItem(Simple03Activity.java:98)

**Comment by bambootang** [comment]
确定为倒影组件创建倒影时内存溢出导致drawingcache未生成bitmap，没有做null验证的问题。
**1.4版本修复，增加为空验证。**
